import { Cable, Plus } from "lucide-react";
import { query } from "@/lib/db";
import { PageHeader, StatusBadge } from "@/components/ui";
import { InterfaceDialog } from "@/components/interface-form";
import { poolStats } from "@/server/ip-allocation";

type Row={id:string;router_id:string;router_name:string;remote_id:string;name:string;listen_port:number;mtu:number;public_key:string;running:boolean;disabled:boolean;addresses:string[];client_pool_start:string|null;client_pool_end:string|null;default_dns:string;default_allowed_ips:string;used_addresses:string[];peers:string};
type RouterOption={id:string;name:string};
export const metadata={title:"WireGuard Interfaces"};
export default async function InterfacesPage({searchParams}:{searchParams:Promise<{create?:string;edit?:string}>}){const p=await searchParams;const [result,routers]=await Promise.all([query<Row>(`SELECT i.*,r.name router_name,count(p.id)::text peers,coalesce(array_agg(p.client_ip) FILTER(WHERE p.client_ip IS NOT NULL),'{}') used_addresses FROM wireguard_interfaces i JOIN routers r ON r.id=i.router_id LEFT JOIN peers p ON p.interface_id=i.id GROUP BY i.id,r.name ORDER BY r.name,i.name`),query<RouterOption>("SELECT id,name FROM routers WHERE enabled=true ORDER BY name")]);const edit=result.rows.find(i=>i.id===p.edit);
 return <><PageHeader title="WireGuard Interfaces" description="Discovered RouterOS interfaces, supported settings, addresses, and collision-safe client pools." actions={<a className="button button-primary" href="/interfaces?create=1"><Plus/>Create interface</a>}/>{result.rows.length?<div className="router-grid">{result.rows.map(i=>{const stats=poolStats(i.client_pool_start,i.client_pool_end,i.used_addresses);return <article className="card router-card" key={i.id}><div className="router-card-top"><div><h3>{i.name}</h3><div className="router-meta">{i.router_name} · {i.remote_id}</div></div><StatusBadge status={i.disabled?"disabled":i.running?"online":"offline"}>{i.disabled?"disabled":i.running?"running":"not running"}</StatusBadge></div><dl className="detail-list"><dt>Listen port / MTU</dt><dd>{i.listen_port} · {i.mtu}</dd><dt>Router addresses</dt><dd className="mono">{i.addresses.length?i.addresses.join(", "):"None discovered"}</dd><dt>Public key</dt><dd className="mono">{i.public_key}</dd><dt>Peers</dt><dd>{i.peers}</dd><dt>Client pool</dt><dd>{i.client_pool_start?`${i.client_pool_start} – ${i.client_pool_end}`:"Not configured"}</dd></dl>{i.client_pool_start&&<><div className="traffic-bar" title={`${stats.used} of ${stats.total} used`}><span style={{width:`${stats.total?Math.min(100,stats.used/stats.total*100):0}%`}}/></div><div className="cell-sub" style={{marginTop:6}}>{stats.used} used · {stats.available} available · {stats.total} total</div></>}<div className="actions" style={{marginTop:14}}><a className="button button-small" href={`/interfaces?edit=${i.id}`}>Edit interface & pool</a></div></article>})}</div>:<div className="card empty"><Cable/><h3>No interfaces discovered</h3><p>Synchronize a RouterOS v7 router or create a supported WireGuard interface.</p></div>}{(p.create==="1"||edit)&&<InterfaceDialog routers={routers.rows} initial={edit?{id:edit.id,name:edit.name,listenPort:edit.listen_port,mtu:edit.mtu,disabled:edit.disabled,clientPoolStart:edit.client_pool_start||"",clientPoolEnd:edit.client_pool_end||"",defaultDns:edit.default_dns,defaultAllowedIps:edit.default_allowed_ips}:undefined}/>}</>}
