import { randomUUID } from "node:crypto";
import { generateWireGuardKeys } from "../wireguard";
import type { CreateRemoteInterface,CreateRemotePeer,CreateRemoteSimpleQueue,RemoteAddress,RemoteFilterRule,RemoteMangleRule,RemoteNatRule,RemoteQueueTree,RemoteRoute,RemoteSimpleQueue,RemoteWireGuardInterface,RemoteWireGuardPeer,RouterClock,RouterFacts,RouterOsClient,UpdateRemoteInterface,UpdateRemotePeer,UpdateRemoteSimpleQueue } from "./types";

const serverKeys=generateWireGuardKeys();
const interfaces:RemoteWireGuardInterface[]=[{id:"*1",name:"wg-demo",listenPort:51820,mtu:1420,publicKey:serverKeys.publicKey,running:true,disabled:false}];
const peers:RemoteWireGuardPeer[]=[];
const simpleQueues:RemoteSimpleQueue[]=[];
export function setMockPeerTraffic(id:string,rxBytes:bigint,txBytes:bigint,lastHandshakeAt:Date|null=new Date()){const peer=peers.find(item=>item.id===id);if(!peer)throw new Error("no such item");peer.rxBytes=rxBytes;peer.txBytes=txBytes;peer.lastHandshakeAt=lastHandshakeAt;peer.lastHandshakeRaw=lastHandshakeAt?"1s":null;peer.lastHandshakeParseValid=true}
export class MockRouterOsClient implements RouterOsClient{
 async testConnection():Promise<RouterFacts>{return{identity:"Demo MikroTik",version:"7.21.1 (stable)",architecture:"arm64",boardName:"RB5009UG+S+",uptime:"2d4h12m",wireguardSupported:true}}
 async getClock():Promise<RouterClock>{const now=new Date();return{date:now.toISOString().slice(0,10),time:now.toISOString().slice(11,19),timeZoneName:"UTC"}}
 async getInterfaces(){return structuredClone(interfaces)}async getPeers(){return peers.map(p=>({...p}))}async getAddresses():Promise<RemoteAddress[]>{return[{id:"*A",interfaceName:"wg-demo",address:"10.44.0.1/24",disabled:false}]}async getRoutes():Promise<RemoteRoute[]>{return[]}async getNatRules():Promise<RemoteNatRule[]>{return[]}
 async getSimpleQueues(){return simpleQueues.map(item=>({...item}))}async getQueueTrees():Promise<RemoteQueueTree[]>{return[]}async getMangleRules():Promise<RemoteMangleRule[]>{return[]}async getFilterRules():Promise<RemoteFilterRule[]>{return[]}
 async createPeer(input:CreateRemotePeer){const id=`*${randomUUID().slice(0,6)}`;peers.push({id,interfaceName:input.interfaceName,name:input.comment,comment:input.comment,publicKey:input.publicKey,allowedAddress:input.allowedAddress,endpointAddress:null,endpointPort:null,persistentKeepalive:input.persistentKeepalive,disabled:Boolean(input.disabled),lastHandshakeAt:null,lastHandshakeRaw:null,lastHandshakeParseValid:true,rxBytes:0n,txBytes:0n});return id}
 async updatePeer(id:string,input:UpdateRemotePeer){const peer=peers.find(p=>p.id===id);if(!peer)throw new Error("no such item");if(input.interfaceName!==undefined)peer.interfaceName=input.interfaceName;if(input.publicKey!==undefined)peer.publicKey=input.publicKey;if(input.allowedAddress!==undefined)peer.allowedAddress=input.allowedAddress;if(input.comment!==undefined){peer.comment=input.comment;peer.name=input.comment}if(input.persistentKeepalive!==undefined)peer.persistentKeepalive=input.persistentKeepalive;if(input.disabled!==undefined)peer.disabled=input.disabled;if(input.endpointAddress!==undefined)peer.endpointAddress=input.endpointAddress;if(input.endpointPort!==undefined)peer.endpointPort=input.endpointPort}
 async deletePeer(id:string){const index=peers.findIndex(p=>p.id===id);if(index<0)throw new Error("no such item");peers.splice(index,1)}
 async createInterface(input:CreateRemoteInterface){const id=`*${randomUUID().slice(0,6)}`;interfaces.push({id,name:input.name,listenPort:input.listenPort,mtu:input.mtu,publicKey:generateWireGuardKeys().publicKey,running:!input.disabled,disabled:Boolean(input.disabled)});return id}
 async updateInterface(id:string,input:UpdateRemoteInterface){const item=interfaces.find(i=>i.id===id);if(!item)throw new Error("no such item");Object.assign(item,{name:input.name??item.name,listenPort:input.listenPort??item.listenPort,mtu:input.mtu??item.mtu,disabled:input.disabled??item.disabled,running:input.disabled===undefined?item.running:!input.disabled})}
 async createSimpleQueue(input:CreateRemoteSimpleQueue){const id=`*${randomUUID().slice(0,6)}`;simpleQueues.push({id,name:input.name,target:input.target,maxLimit:input.maxLimit,burstLimit:input.burstLimit??"0/0",burstThreshold:input.burstThreshold??"0/0",burstTime:input.burstTime??"0s/0s",disabled:Boolean(input.disabled),comment:input.comment,dynamic:false,invalid:false});return id}
 async updateSimpleQueue(id:string,input:UpdateRemoteSimpleQueue){const item=simpleQueues.find(queue=>queue.id===id);if(!item)throw new Error("no such item");Object.assign(item,{name:input.name??item.name,target:input.target??item.target,maxLimit:input.maxLimit??item.maxLimit,burstLimit:input.burstLimit??item.burstLimit,burstThreshold:input.burstThreshold??item.burstThreshold,burstTime:input.burstTime??item.burstTime,disabled:input.disabled??item.disabled,comment:input.comment??item.comment})}
 async deleteSimpleQueue(id:string){const index=simpleQueues.findIndex(queue=>queue.id===id);if(index<0)throw new Error("no such item");simpleQueues.splice(index,1)}
 async close(){}
}
