import { notFound } from "next/navigation";
import { Activity, Clock, Download, Router, Waypoints } from "lucide-react";
import { query } from "@/lib/db";
import { formatBytes, peerStatus } from "@/server/status";
import { Metric, PageHeader, StatusBadge } from "@/components/ui";
import { PeerDetailActions } from "@/components/peer-detail-actions";
import { getStatusThresholds } from "@/server/settings";

type Peer={id:string;name:string;description:string|null;origin:string;public_key:string;private_key_encrypted:string|null;client_ip:string|null;allowed_address:string;client_allowed_ips:string;dns_server:string;endpoint_override:string|null;endpoint_port_override:number|null;persistent_keepalive:number;mtu:number;disabled:boolean;expired:boolean;expires_at:Date|null;last_handshake_at:Date|null;last_seen_at:Date|null;rx_bytes:string;tx_bytes:string;conflict_type:string|null;conflict_details:unknown;created_at:Date;updated_at:Date;router_name:string;management_ip:string;endpoint_hostname:string|null;endpoint_ip:string|null;wireguard_port:number|null;interface_name:string;listen_port:number};
export default async function PeerDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const [result,history,audits,thresholds]=await Promise.all([query<Peer>(`SELECT p.*,r.name router_name,r.management_ip,r.endpoint_hostname,r.endpoint_ip,r.wireguard_port,i.name interface_name,i.listen_port FROM peers p JOIN routers r ON r.id=p.router_id JOIN wireguard_interfaces i ON i.id=p.interface_id WHERE p.id=$1`,[id]),query<{captured_at:Date;rx_bytes:string;tx_bytes:string;last_handshake_at:Date|null}>("SELECT captured_at,rx_bytes,tx_bytes,last_handshake_at FROM traffic_snapshots WHERE peer_id=$1 ORDER BY captured_at DESC LIMIT 10",[id]),query<{created_at:Date;username:string|null;action:string;result:string}>("SELECT created_at,username,action,result FROM audit_logs WHERE peer_id=$1 ORDER BY created_at DESC LIMIT 12",[id]),getStatusThresholds()]);const p=result.rows[0];if(!p)notFound();const status=peerStatus(p,new Date(),thresholds);const endpoint=p.endpoint_override||p.endpoint_hostname||p.endpoint_ip||p.management_ip;const port=p.endpoint_port_override||p.listen_port;
 const actionPeer={id:p.id,name:p.name,description:p.description||"",allowedAddress:p.allowed_address,clientAllowedIps:p.client_allowed_ips,dnsServer:p.dns_server,persistentKeepalive:p.persistent_keepalive,mtu:p.mtu,expiresAt:p.expires_at?.toISOString()||null,endpointOverride:p.endpoint_override||"",endpointPortOverride:p.endpoint_port_override,disabled:p.disabled,managed:Boolean(p.private_key_encrypted)};
 return <><PageHeader title={p.name} description={`${p.router_name} / ${p.interface_name} · ${p.origin} peer`} actions={<StatusBadge status={status}/>}/>{p.conflict_type&&<div className="conflict"><strong>Synchronization conflict: {p.conflict_type.replaceAll("_"," ")}</strong><div>This peer changed outside WireGuard Control. Review and synchronize before applying a mutation; external changes will not be overwritten silently.</div></div>}<PeerDetailActions peer={actionPeer}/>
 <section className="metrics" style={{marginTop:18}}><Metric label="Total traffic" value={formatBytes(BigInt(p.rx_bytes)+BigInt(p.tx_bytes))} foot={`RX ${formatBytes(p.rx_bytes)} · TX ${formatBytes(p.tx_bytes)}`} icon={Activity}/><Metric label="Client address" value={<span className="mono">{p.client_ip||"—"}</span>} foot={p.allowed_address} icon={Waypoints}/><Metric label="Last handshake" value={p.last_handshake_at?new Date(p.last_handshake_at).toLocaleTimeString():"Never"} foot={p.last_handshake_at?new Date(p.last_handshake_at).toLocaleDateString():"No connection observed"} icon={Clock}/><Metric label="Endpoint" value={<span className="mono" style={{fontSize:16}}>{endpoint}:{port}</span>} foot="Generated client endpoint" icon={Router}/></section>
 <div className="grid-sidebar"><section className="card"><div className="card-header"><h2>Peer details</h2>{p.private_key_encrypted&&<a className="button button-small" href={`/api/peers/${p.id}/config`}><Download/>Config</a>}</div><div className="card-body"><dl className="detail-list"><dt>Status / origin</dt><dd><StatusBadge status={status}/> <StatusBadge status={p.origin}/></dd><dt>Router</dt><dd>{p.router_name}</dd><dt>Interface</dt><dd>{p.interface_name}</dd><dt>Public key</dt><dd className="mono">{p.public_key}</dd><dt>Client IP</dt><dd className="mono">{p.client_ip||"—"}</dd><dt>Allowed address</dt><dd className="mono">{p.allowed_address}</dd><dt>Client AllowedIPs</dt><dd className="mono">{p.client_allowed_ips}</dd><dt>DNS</dt><dd className="mono">{p.dns_server}</dd><dt>Keepalive / MTU</dt><dd>{p.persistent_keepalive}s · {p.mtu}</dd><dt>Created</dt><dd>{new Date(p.created_at).toLocaleString()}</dd><dt>Expiration</dt><dd>{p.expires_at?new Date(p.expires_at).toLocaleString():"Never"}</dd><dt>Last seen</dt><dd>{p.last_seen_at?new Date(p.last_seen_at).toLocaleString():"Never"}</dd></dl></div></section><aside className="card"><div className="card-header"><h2>Recent activity</h2></div><div className="card-body">{audits.rows.length?audits.rows.map((a,i)=><div key={i} style={{padding:"10px 0",borderBottom:"1px solid var(--border)"}}><div className="cell-main">{a.action.replaceAll("_"," ")}</div><div className="cell-sub">{a.username||"system"} · {new Date(a.created_at).toLocaleString()}</div></div>):<div className="cell-sub">No recorded administrative activity.</div>}</div></aside></div>
 {history.rows.length>0&&<section className="card" style={{marginTop:16}}><div className="card-header"><h2>Traffic snapshots</h2></div><div className="table-wrap"><table><thead><tr><th>Captured</th><th>RX</th><th>TX</th><th>Total</th><th>Last handshake</th></tr></thead><tbody>{history.rows.map((h,i)=><tr key={i}><td>{new Date(h.captured_at).toLocaleString()}</td><td>{formatBytes(h.rx_bytes)}</td><td>{formatBytes(h.tx_bytes)}</td><td>{formatBytes(BigInt(h.rx_bytes)+BigInt(h.tx_bytes))}</td><td>{h.last_handshake_at?new Date(h.last_handshake_at).toLocaleString():"Never"}</td></tr>)}</tbody></table></div></section>}</>}
