import { Activity, AlertTriangle, ArrowDown, ArrowUp, ArrowUpDown, CheckCircle2, Clock3, HeartPulse, Router, ServerCog, ShieldAlert, Waypoints } from "lucide-react";
import Link from "next/link";
import { query } from "@/lib/db";
import { DriftActions } from "@/components/drift-actions";
import { Metric, PageHeader, StatusBadge } from "@/components/ui";

type Summary={routers:string;connected:string;offline:string;drifts:string;quota_risk:string;missing_queues:string;expired:string;pending_operations:string};
type Job={job_name:string;status:string;last_started_at:Date|null;last_success_at:Date|null;last_failure_at:Date|null;last_error:string|null;consecutive_failures:number;next_run_at:Date|null;last_duration_ms:number|null};
type RouterHealth={id:string;name:string;connection_status:string;api_latency_ms:number|null;last_successful_connection_at:Date|null;last_synced_at:Date|null;last_failed_operation_at:Date|null;last_failed_operation:string|null;routeros_version:string|null;clock_difference_seconds:number|null;peer_count:string;sync_conflicts:string;consecutive_failures:number;next_retry_at:Date|null};
type Drift={id:string;object_type:string;state:string;peer_id:string|null;peer_name:string|null;router_name:string;differences:Array<{field:string;application:unknown;lastSynchronized?:unknown;router:unknown}>;detected_at:Date};
type Operation={id:string;operation_type:string;status:string;peer_name:string|null;router_name:string|null;last_error:string|null;retry_count:number;next_retry_at:Date|null;started_at:Date;updated_at:Date};
export const metadata={title:"Operations / System Health"};

export default async function OperationsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const p=await searchParams;
  const jobSort=validSort(p.jobSort,["job","status","success","failure","duration","next"],"job_asc");
  const routerSort=validSort(p.routerSort,["router","connection","latency","success","peers","retry"],"router_asc");
  const operationSort=validSort(p.operationSort,["operation","object","status","started","retry","error"],"started_desc");
  const jobOrder:Record<string,string>={job_asc:"job_name ASC",job_desc:"job_name DESC",status_asc:"status ASC,job_name ASC",status_desc:"status DESC,job_name ASC",success_asc:"last_success_at ASC NULLS LAST",success_desc:"last_success_at DESC NULLS LAST",failure_asc:"last_failure_at ASC NULLS LAST",failure_desc:"last_failure_at DESC NULLS LAST",duration_asc:"last_duration_ms ASC NULLS LAST",duration_desc:"last_duration_ms DESC NULLS LAST",next_asc:"next_run_at ASC NULLS LAST",next_desc:"next_run_at DESC NULLS LAST"};
  const routerOrder:Record<string,string>={router_asc:"r.name ASC",router_desc:"r.name DESC",connection_asc:"r.connection_status ASC,r.name ASC",connection_desc:"r.connection_status DESC,r.name ASC",latency_asc:"r.api_latency_ms ASC NULLS LAST",latency_desc:"r.api_latency_ms DESC NULLS LAST",success_asc:"r.last_successful_connection_at ASC NULLS LAST",success_desc:"r.last_successful_connection_at DESC NULLS LAST",peers_asc:"peer_count ASC",peers_desc:"peer_count DESC",retry_asc:"r.consecutive_failures ASC",retry_desc:"r.consecutive_failures DESC"};
  const operationOrder:Record<string,string>={operation_asc:"o.operation_type ASC",operation_desc:"o.operation_type DESC",object_asc:"COALESCE(p.name,'') ASC",object_desc:"COALESCE(p.name,'') DESC",status_asc:"o.status ASC",status_desc:"o.status DESC",started_asc:"o.started_at ASC",started_desc:"o.started_at DESC",retry_asc:"o.retry_count ASC",retry_desc:"o.retry_count DESC",error_asc:"o.last_error ASC NULLS LAST",error_desc:"o.last_error DESC NULLS LAST"};
  const[summary,jobs,routers,drifts,operations]=await Promise.all([
    query<Summary>(`SELECT (SELECT count(*) FROM routers WHERE enabled)::text routers,(SELECT count(*) FROM routers WHERE enabled AND connection_status='connected')::text connected,
      (SELECT count(*) FROM routers WHERE enabled AND connection_status<>'connected')::text offline,(SELECT count(*) FROM configuration_drifts WHERE resolved_at IS NULL)::text drifts,
      (SELECT count(*) FROM peers WHERE quota_limit_bytes IS NOT NULL AND (period_rx_bytes+period_tx_bytes)*100>=quota_limit_bytes*90)::text quota_risk,
      (SELECT count(*) FROM peers WHERE bandwidth_sync_state IN ('missing','duplicate','conflict','changed_externally','error'))::text missing_queues,
      (SELECT count(*) FROM peers WHERE expired)::text expired,(SELECT count(*) FROM management_operations WHERE status IN ('partial','needs_reconciliation','pending_cleanup'))::text pending_operations`),
    query<Job>(`SELECT * FROM worker_job_health ORDER BY ${jobOrder[jobSort]}`),
    query<RouterHealth>(`SELECT r.id,r.name,r.connection_status,r.api_latency_ms,r.last_successful_connection_at,r.last_synced_at,r.last_failed_operation_at,
      r.last_failed_operation,r.routeros_version,r.clock_difference_seconds,r.consecutive_failures,r.next_retry_at,count(p.id)::text peer_count,
      count(p.id) FILTER(WHERE p.sync_state IN ('changed_externally','conflict','error'))::text sync_conflicts FROM routers r LEFT JOIN peers p ON p.router_id=r.id GROUP BY r.id ORDER BY ${routerOrder[routerSort]}`),
    query<Drift>(`SELECT d.id,d.object_type,d.state,d.peer_id,p.name peer_name,r.name router_name,d.differences,d.detected_at
      FROM configuration_drifts d JOIN routers r ON r.id=d.router_id LEFT JOIN peers p ON p.id=d.peer_id WHERE d.resolved_at IS NULL ORDER BY d.detected_at DESC LIMIT 50`),
    query<Operation>(`SELECT o.id,o.operation_type,o.status,p.name peer_name,r.name router_name,o.last_error,o.retry_count,o.next_retry_at,o.started_at,o.updated_at
      FROM management_operations o LEFT JOIN peers p ON p.id=o.peer_id LEFT JOIN routers r ON r.id=o.router_id ORDER BY ${operationOrder[operationSort]} LIMIT 50`),
  ]);const s=summary.rows[0];
  return <><PageHeader title="Operations / System Health" description="Worker execution, RouterOS reachability, durable operations, and configuration drift in one control surface."/>
    <section className="metrics"><Metric label="Routers" value={`${s.connected} / ${s.routers}`} foot={`${s.offline} unavailable`} icon={Router}/><Metric label="Open drift" value={s.drifts} foot="Requires review; never auto-overwritten" icon={ShieldAlert}/><Metric label="Pending operations" value={s.pending_operations} foot="Automatic cleanup and reconciliation" icon={ServerCog}/><Metric label="Quota risk" value={s.quota_risk} foot="Peers at or above 90%" icon={Activity}/></section>
    <section className="card"><div className="card-header"><div><h2>Background workers</h2><p>Independent schedules prevent one router or job from blocking the others.</p></div><StatusBadge status={jobs.rows.every(job=>job.status==="healthy")?"online":"warning"}>{jobs.rows.filter(job=>job.status==="healthy").length}/{jobs.rows.length} healthy</StatusBadge></div><div className="table-wrap"><table><thead><tr><OpsSortHeader label="Job" field="job" param="jobSort" current={jobSort} preserve={{routerSort,operationSort}}/><OpsSortHeader label="Status" field="status" param="jobSort" current={jobSort} preserve={{routerSort,operationSort}}/><OpsSortHeader label="Last success" field="success" param="jobSort" current={jobSort} preserve={{routerSort,operationSort}}/><OpsSortHeader label="Last failure" field="failure" param="jobSort" current={jobSort} preserve={{routerSort,operationSort}}/><OpsSortHeader label="Duration" field="duration" param="jobSort" current={jobSort} preserve={{routerSort,operationSort}}/><OpsSortHeader label="Next run" field="next" param="jobSort" current={jobSort} preserve={{routerSort,operationSort}}/></tr></thead><tbody>{jobs.rows.map(job=><tr key={job.job_name}><td><strong>{job.job_name.replaceAll("_"," ")}</strong>{job.last_error&&<div className="cell-sub cell-danger">{job.last_error}</div>}</td><td><StatusBadge status={job.status}/>{job.consecutive_failures>0&&<span className="cell-sub"> {job.consecutive_failures} consecutive</span>}</td><td>{time(job.last_success_at)}</td><td>{time(job.last_failure_at)}</td><td>{job.last_duration_ms==null?"—":`${job.last_duration_ms.toLocaleString()} ms`}</td><td>{time(job.next_run_at)}</td></tr>)}</tbody></table></div></section>
    <section className="card" style={{marginTop:16}}><div className="card-header"><h2>Router health</h2><Link className="button button-small" href="/routers">Manage routers</Link></div><div className="table-wrap"><table><thead><tr><OpsSortHeader label="Router" field="router" param="routerSort" current={routerSort} preserve={{jobSort,operationSort}}/><OpsSortHeader label="Connection" field="connection" param="routerSort" current={routerSort} preserve={{jobSort,operationSort}}/><OpsSortHeader label="Latency / clock" field="latency" param="routerSort" current={routerSort} preserve={{jobSort,operationSort}}/><OpsSortHeader label="Last success" field="success" param="routerSort" current={routerSort} preserve={{jobSort,operationSort}}/><OpsSortHeader label="Peer sync" field="peers" param="routerSort" current={routerSort} preserve={{jobSort,operationSort}}/><OpsSortHeader label="Retry" field="retry" param="routerSort" current={routerSort} preserve={{jobSort,operationSort}}/></tr></thead><tbody>{routers.rows.map(router=><tr key={router.id}><td><Link href={`/routers/${router.id}`}><strong>{router.name}</strong></Link><div className="cell-sub">RouterOS {router.routeros_version??"unknown"}</div></td><td><StatusBadge status={router.connection_status}/>{router.last_failed_operation&&<div className="cell-sub cell-danger">{router.last_failed_operation}</div>}</td><td>{router.api_latency_ms==null?"—":`${router.api_latency_ms} ms`}<div className="cell-sub">Clock {router.clock_difference_seconds==null?"unknown":`${signed(router.clock_difference_seconds)}s`}</div></td><td>{time(router.last_successful_connection_at)}<div className="cell-sub">Sync {time(router.last_synced_at)}</div></td><td>{router.peer_count} peers<div className="cell-sub">{router.sync_conflicts} conflicts</div></td><td>{router.consecutive_failures?`${router.consecutive_failures} failures`:"Ready"}<div className="cell-sub">{router.next_retry_at?`Next ${time(router.next_retry_at)}`:"No backoff"}</div></td></tr>)}</tbody></table></div></section>
    <section className="grid-sidebar" style={{marginTop:16}}><div className="card"><div className="card-header"><div><h2>Needs attention</h2><p>Field-level RouterOS differences.</p></div><span className="status-chip status-warning"><AlertTriangle/> {drifts.rows.length}</span></div><div className="card-body drift-list">{drifts.rows.length?drifts.rows.map(drift=><article className="drift-card" key={drift.id}><div className="drift-card-head"><div><strong>{drift.peer_name??drift.object_type}</strong><div className="cell-sub">{drift.router_name} · {drift.object_type} · detected {time(drift.detected_at)}</div></div><StatusBadge status={drift.state}/></div><div className="table-wrap"><table className="compact-table"><thead><tr><th>Field</th><th>Application</th><th>RouterOS</th></tr></thead><tbody>{drift.differences.map((difference,index)=><tr key={`${difference.field}-${index}`}><td>{difference.field}</td><td className="mono">{show(difference.application)}</td><td className="mono">{show(difference.router)}</td></tr>)}</tbody></table></div><DriftActions id={drift.id}/></article>):<div className="empty-inline"><CheckCircle2/>No open configuration drift.</div>}</div></div>
      <aside className="card"><div className="card-header"><h2>Attention summary</h2></div><div className="card-body"><dl className="detail-list"><dt><Router/> Routers offline</dt><dd>{s.offline}</dd><dt><ShieldAlert/> Sync conflicts</dt><dd>{s.drifts}</dd><dt><Activity/> Peers above 90%</dt><dd>{s.quota_risk}</dd><dt><Waypoints/> Bandwidth issues</dt><dd>{s.missing_queues}</dd><dt><Clock3/> Expired peers</dt><dd>{s.expired}</dd><dt><HeartPulse/> Pending cleanup</dt><dd>{s.pending_operations}</dd></dl></div></aside></section>
    <section className="card" style={{marginTop:16}}><div className="card-header"><h2>Recent managed operations</h2></div><div className="table-wrap"><table><thead><tr><OpsSortHeader label="Operation" field="operation" param="operationSort" current={operationSort} preserve={{jobSort,routerSort}}/><OpsSortHeader label="Object" field="object" param="operationSort" current={operationSort} preserve={{jobSort,routerSort}}/><OpsSortHeader label="Status" field="status" param="operationSort" current={operationSort} preserve={{jobSort,routerSort}}/><OpsSortHeader label="Started" field="started" param="operationSort" current={operationSort} preserve={{jobSort,routerSort}}/><OpsSortHeader label="Retry" field="retry" param="operationSort" current={operationSort} preserve={{jobSort,routerSort}}/><OpsSortHeader label="Last error" field="error" param="operationSort" current={operationSort} preserve={{jobSort,routerSort}}/></tr></thead><tbody>{operations.rows.map(operation=><tr key={operation.id}><td><strong>{operation.operation_type.replaceAll("_"," ")}</strong><div className="cell-sub mono">{operation.id.slice(0,8)}</div></td><td>{operation.peer_name??"Peer record removed"}<div className="cell-sub">{operation.router_name??"—"}</div></td><td><StatusBadge status={operation.status}/></td><td>{time(operation.started_at)}</td><td>{operation.retry_count}{operation.next_retry_at&&<div className="cell-sub">{time(operation.next_retry_at)}</div>}</td><td className="cell-danger">{operation.last_error??"—"}</td></tr>)}</tbody></table></div></section>
  </>;
}
function time(value:Date|null){return value?new Date(value).toLocaleString():"Never"}function signed(value:number){return value>0?`+${value}`:String(value)}function show(value:unknown){if(value===null||value===undefined)return"—";if(typeof value==="object")return JSON.stringify(value);return String(value)}
function validSort(value:string|undefined,fields:string[],fallback:string){const[field,direction]=String(value??"").split("_");return fields.includes(field)&&(direction==="asc"||direction==="desc")?`${field}_${direction}`:fallback}
function OpsSortHeader({label,field,param,current,preserve}:{label:string;field:string;param:"jobSort"|"routerSort"|"operationSort";current:string;preserve:Record<string,string>}){const[active,direction]=current.split("_");const isActive=active===field;const next=isActive&&direction==="asc"?"desc":"asc";const params=new URLSearchParams(preserve);params.set(param,`${field}_${next}`);const Icon=!isActive?ArrowUpDown:direction==="asc"?ArrowUp:ArrowDown;return <th aria-sort={isActive?(direction==="asc"?"ascending":"descending"):"none"}><Link className="sort-link" href={`?${params.toString()}`}>{label}<Icon aria-hidden="true"/></Link></th>}
