import {redirect} from "next/navigation";
import {ArrowDown,ArrowUp,ArrowUpDown,Users} from "lucide-react";
import Link from "next/link";
import {requireUser} from "@/lib/auth";
import {query} from "@/lib/db";
import {PageHeader,StatusBadge} from "@/components/ui";
import {UserManagement} from "@/components/user-management";

type Row={id:string;username:string;role:"super_admin"|"administrator"|"read_only";enabled:boolean;last_login_at:Date|null;created_at:Date};
export const metadata={title:"User access"};
export default async function UsersPage({searchParams}:{searchParams:Promise<{sort?:string}>}){const auth=await requireUser("user:manage");if(!auth.user)redirect("/dashboard");const p=await searchParams;const sort=validSort(p.sort);const orders:Record<string,string>={username_asc:"username ASC",username_desc:"username DESC",role_asc:"role ASC,username ASC",role_desc:"role DESC,username ASC",enabled_asc:"enabled ASC,username ASC",enabled_desc:"enabled DESC,username ASC",login_asc:"last_login_at ASC NULLS LAST",login_desc:"last_login_at DESC NULLS LAST",created_asc:"created_at ASC",created_desc:"created_at DESC"};const users=await query<Row>(`SELECT id,username,role,enabled,last_login_at,created_at FROM users ORDER BY ${orders[sort]}`);return <><PageHeader title="User access" description="Role-based administrative access. Read Only accounts cannot retrieve private WireGuard configurations or QR codes."/><section className="metrics"><div className="metric"><div className="metric-head"><span>Accounts</span><span className="metric-icon"><Users/></span></div><strong className="metric-value">{users.rows.length}</strong><div className="metric-foot">{users.rows.filter(user=>user.enabled).length} enabled</div></div>{(["super_admin","administrator","read_only"] as const).map(role=><div className="metric" key={role}><div className="metric-head"><span>{label(role)}</span><StatusBadge status={users.rows.some(user=>user.role===role&&user.enabled)?"online":"disabled"}/></div><strong className="metric-value">{users.rows.filter(user=>user.role===role).length}</strong><div className="metric-foot">configured accounts</div></div>)}</section><section className="card"><div className="card-header"><div><h2>Accounts and roles</h2><p>Disabling an account or changing its role revokes active sessions.</p></div></div><div className="card-body"><div className="user-sort-links">Sort: <Sort label="Username" field="username" current={sort}/><Sort label="Role" field="role" current={sort}/><Sort label="Enabled" field="enabled" current={sort}/><Sort label="Last login" field="login" current={sort}/><Sort label="Created" field="created" current={sort}/></div><UserManagement currentUserId={auth.user.id} users={users.rows.map(user=>({id:user.id,username:user.username,role:user.role,enabled:user.enabled,lastLoginAt:user.last_login_at?.toISOString()??null,createdAt:user.created_at.toISOString()}))}/></div></section></>}
function validSort(value:string|undefined){return /^(username|role|enabled|login|created)_(asc|desc)$/.test(value??"")?value!:"username_asc"}function label(role:string){return role.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase())}function Sort({label,field,current}:{label:string;field:string;current:string}){const[active,direction]=current.split("_");const isActive=active===field;const next=isActive&&direction==="asc"?"desc":"asc";const Icon=!isActive?ArrowUpDown:direction==="asc"?ArrowUp:ArrowDown;return <Link className="button button-small" href={`?sort=${field}_${next}`}>{label}<Icon/></Link>}
