import { Activity, ArrowDownToLine, ArrowUpFromLine, Radio } from "lucide-react";
import { query } from "@/lib/db";
import { formatBytes } from "@/server/status";
import { Metric, PageHeader, StatusBadge } from "@/components/ui";
import { getStatusThresholds } from "@/server/settings";

type Totals={rx:string;tx:string;active:string;snapshots:string};
type Row={id:string;name:string;router_name:string;interface_name:string;rx_bytes:string;tx_bytes:string;last_handshake_at:Date|null;status:string;last_synced_at:Date|null};
export const metadata={title:"Traffic"};
export default async function TrafficPage(){const thresholds=await getStatusThresholds();const [totals,rows]=await Promise.all([query<Totals>(`SELECT coalesce(sum(rx_bytes),0)::text rx,coalesce(sum(tx_bytes),0)::text tx,count(*) FILTER(WHERE disabled=false AND expired=false AND last_handshake_at>now()-make_interval(secs=>$1))::text active,(SELECT count(*) FROM traffic_snapshots)::text snapshots FROM peers`,[thresholds.onlineSeconds]),query<Row>(`SELECT p.id,p.name,r.name router_name,i.name interface_name,p.rx_bytes,p.tx_bytes,p.last_handshake_at,p.last_synced_at,CASE WHEN p.expired THEN 'expired' WHEN p.disabled THEN 'disabled' WHEN p.last_handshake_at IS NULL THEN 'never' WHEN p.last_handshake_at>now()-make_interval(secs=>$1) THEN 'online' WHEN p.last_handshake_at>now()-make_interval(secs=>$2) THEN 'recent' ELSE 'offline' END status FROM peers p JOIN routers r ON r.id=p.router_id JOIN wireguard_interfaces i ON i.id=p.interface_id ORDER BY (p.rx_bytes+p.tx_bytes) DESC LIMIT 200`,[thresholds.onlineSeconds,thresholds.recentSeconds])]);const t=totals.rows[0];return <><PageHeader title="Traffic" description="RouterOS transfer counters and handshake presence from the latest synchronization."/><section className="metrics"><Metric label="Received" value={formatBytes(t.rx)} foot="Aggregate peer RX" icon={ArrowDownToLine}/><Metric label="Transmitted" value={formatBytes(t.tx)} foot="Aggregate peer TX" icon={ArrowUpFromLine}/><Metric label="Active peers" value={t.active} foot={`Handshake within ${thresholds.onlineSeconds}s`} icon={Radio}/><Metric label="Snapshots" value={t.snapshots} foot="Historical samples retained" icon={Activity}/></section><section className="card"><div className="card-header"><h2>Peer usage</h2><span className="cell-sub">Last updated during router synchronization</span></div><div className="table-wrap"><table><thead><tr><th>Peer</th><th>Status</th><th>RX</th><th>TX</th><th>Total</th><th>Last handshake</th><th>Statistics updated</th></tr></thead><tbody>{rows.rows.map(p=><tr key={p.id}><td><div className="cell-main"><a href={`/peers/${p.id}`}>{p.name}</a></div><div className="cell-sub">{p.router_name} / {p.interface_name}</div></td><td><StatusBadge status={p.status}/></td><td>{formatBytes(p.rx_bytes)}</td><td>{formatBytes(p.tx_bytes)}</td><td><strong>{formatBytes(BigInt(p.rx_bytes)+BigInt(p.tx_bytes))}</strong></td><td>{p.last_handshake_at?new Date(p.last_handshake_at).toLocaleString():"Never"}</td><td>{p.last_synced_at?new Date(p.last_synced_at).toLocaleString():"Never"}</td></tr>)}</tbody></table></div></section></>}
