"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { LoaderCircle, Save, X } from "lucide-react";
import { api } from "@/lib/client-api";

type Option={id:string;name:string;routerId?:string;routerName?:string;defaultDns?:string;defaultAllowedIps?:string;mtu?:number;poolStart?:string|null;poolEnd?:string|null};
export function PeerCreateDialog({routers,interfaces}:{routers:Option[];interfaces:Option[]}){const router=useRouter();const [routerId,setRouterId]=useState(routers[0]?.id||"");const available=useMemo(()=>interfaces.filter(i=>i.routerId===routerId),[interfaces,routerId]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const close=()=>router.push("/peers");
 return <div className="dialog-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="new-peer-title"><header className="dialog-header"><div><h2 id="new-peer-title">Create WireGuard peer</h2><p>The address is checked against both RouterOS and the database before allocation.</p></div><button className="button button-ghost icon-button" onClick={close} aria-label="Close"><X/></button></header><form onSubmit={async e=>{e.preventDefault();setLoading(true);setError("");const data=new FormData(e.currentTarget);try{const result=await api<{id:string}>("/api/peers",{method:"POST",body:JSON.stringify({routerId,interfaceId:data.get("interfaceId"),name:data.get("name"),description:data.get("description"),requestedIp:data.get("requestedIp")||undefined,clientAllowedIps:data.get("clientAllowedIps"),dnsServer:data.get("dnsServer"),persistentKeepalive:Number(data.get("persistentKeepalive")),mtu:Number(data.get("mtu")),expiresAt:data.get("expiresAt")?new Date(String(data.get("expiresAt"))).toISOString():null,usePresharedKey:data.get("usePresharedKey")==="on"})});router.push(`/peers/${result.id}`);router.refresh()}catch(err){setError(err instanceof Error?err.message:"Create failed")}finally{setLoading(false)}}}><div className="dialog-body form"><div className="form-grid">
 <div className="form-group"><label className="label" htmlFor="peer-router">Router</label><select id="peer-router" className="field" required value={routerId} onChange={e=>setRouterId(e.target.value)}>{routers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div>
 <div className="form-group"><label className="label" htmlFor="peer-interface">WireGuard interface</label><select id="peer-interface" className="field" name="interfaceId" required>{available.map(i=><option key={i.id} value={i.id}>{i.name} {i.poolStart?`(${i.poolStart}–${i.poolEnd})`:"(pool not set)"}</option>)}</select></div>
 <div className="form-group"><label className="label" htmlFor="peer-name">Name</label><input id="peer-name" className="field" name="name" required placeholder="Amir phone"/></div>
 <div className="form-group"><label className="label" htmlFor="requested-ip">Client IP <span className="hint">(optional)</span></label><input id="requested-ip" className="field mono" name="requestedIp" placeholder="Auto-allocate next address"/></div>
 <div className="form-group span-2"><label className="label" htmlFor="description">Description</label><textarea id="description" className="field" name="description" rows={2}/></div>
 <div className="form-group"><label className="label" htmlFor="client-allowed">Client AllowedIPs</label><input id="client-allowed" className="field mono" name="clientAllowedIps" defaultValue={available[0]?.defaultAllowedIps||"0.0.0.0/0"} required/></div>
 <div className="form-group"><label className="label" htmlFor="dns-server">DNS server</label><input id="dns-server" className="field mono" name="dnsServer" defaultValue={available[0]?.defaultDns||"1.1.1.1"} required/></div>
 <div className="form-group"><label className="label" htmlFor="keepalive">Persistent keepalive</label><input id="keepalive" className="field" name="persistentKeepalive" type="number" min="0" max="65535" defaultValue="25"/></div>
 <div className="form-group"><label className="label" htmlFor="peer-mtu">MTU</label><input id="peer-mtu" className="field" name="mtu" type="number" min="576" max="9000" defaultValue={available[0]?.mtu||1420}/></div>
 <div className="form-group"><label className="label" htmlFor="expires-at">Expires at <span className="hint">(optional)</span></label><input id="expires-at" className="field" name="expiresAt" type="datetime-local"/></div>
 <div className="form-group"><div className="checkbox"><input id="psk" name="usePresharedKey" type="checkbox"/><label htmlFor="psk">Add a pre-shared key</label></div></div>
 </div>{!available.length&&<div className="form-message form-message-error">This router has no discovered WireGuard interface. Synchronize it first.</div>}{error&&<div className="form-message form-message-error" role="alert">{error}</div>}</div><footer className="dialog-footer"><button type="button" className="button" onClick={close}>Cancel</button><button className="button button-primary" disabled={loading||!available.length}>{loading?<LoaderCircle className="spin"/>:<Save/>}{loading?"Creating on MikroTik…":"Create peer"}</button></footer></form></section></div>}
