"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Download, Eye, LoaderCircle, Power, PowerOff, Trash2 } from "lucide-react";
import { api } from "@/lib/client-api";
import { StatusBadge } from "./ui";

export type PeerTableRow={id:string;name:string;description:string|null;router_name:string;interface_name:string;client_ip:string|null;public_key:string;origin:string;status:string;last_handshake_at:string|null;rx:string;tx:string;traffic:string;conflict_type:string|null};
export function PeerTable({rows}:{rows:PeerTableRow[]}){const router=useRouter();const [selected,setSelected]=useState<string[]>([]);const [loading,setLoading]=useState(false);const all=rows.length>0&&selected.length===rows.length;
 const bulk=async(action:"enable"|"disable"|"delete")=>{if(action==="delete"&&!confirm(`Permanently delete ${selected.length} selected peers from their MikroTik routers and the local database?`))return;setLoading(true);try{const result=await api<{failed:number}>("/api/peers/bulk",{method:"POST",body:JSON.stringify({ids:selected,action})});setSelected([]);router.refresh();if(result.failed)alert(`${result.failed} peer actions failed because of conflicts or router errors.`)}catch(e){alert(e instanceof Error?e.message:"Bulk action failed")}finally{setLoading(false)}};
 return <>{selected.length>0&&<div className="table-toolbar"><strong>{selected.length} selected</strong><button className="button button-small" onClick={()=>bulk("enable")} disabled={loading}><Power/>Enable</button><button className="button button-small" onClick={()=>bulk("disable")} disabled={loading}><PowerOff/>Disable</button><button className="button button-small button-danger" onClick={()=>bulk("delete")} disabled={loading}>{loading?<LoaderCircle className="spin"/>:<Trash2/>}Delete</button></div>}<div className="table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Select all peers" checked={all} onChange={e=>setSelected(e.target.checked?rows.map(r=>r.id):[])}/></th><th>Peer</th><th>Status</th><th>Client IP</th><th>Router / interface</th><th>Last handshake</th><th>Traffic</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(peer=><tr key={peer.id}><td><input type="checkbox" aria-label={`Select ${peer.name}`} checked={selected.includes(peer.id)} onChange={e=>setSelected(e.target.checked?[...selected,peer.id]:selected.filter(id=>id!==peer.id))}/></td><td><div className="cell-main"><a href={`/peers/${peer.id}`}>{peer.name}</a></div><div className="cell-sub">{peer.origin}{peer.conflict_type&&<> · <span style={{color:"var(--warning)"}}>conflict</span></>}</div></td><td><StatusBadge status={peer.status}/></td><td className="mono">{peer.client_ip||"—"}</td><td><div>{peer.router_name}</div><div className="cell-sub">{peer.interface_name}</div></td><td>{peer.last_handshake_at?new Date(peer.last_handshake_at).toLocaleString():"Never"}</td><td><div>{peer.traffic}</div><div className="cell-sub">RX {peer.rx} · TX {peer.tx}</div></td><td><div className="table-actions"><a className="button button-small icon-button" href={`/peers/${peer.id}`} aria-label={`View ${peer.name}`}><Eye/></a>{peer.origin==="managed"&&<a className="button button-small icon-button" href={`/api/peers/${peer.id}/config`} aria-label={`Download ${peer.name} configuration`}><Download/></a>}</div></td></tr>)}</tbody></table></div></>}
