"use client";
import {useState} from "react";
import {Gauge,LoaderCircle,Save,Wrench} from "lucide-react";
import {useRouter} from "next/navigation";
import {api} from "@/lib/client-api";
import {StatusBadge} from "./ui";

type Profile={id:string;name:string;downloadBps:string|null;uploadBps:string|null};
export function PeerBandwidthCard({peerId,downloadBps,uploadBps,source,sourceName,syncState,profiles,canManage}:{peerId:string;downloadBps:string|null;uploadBps:string|null;source:string;sourceName:string;syncState:string;profiles:Profile[];canManage:boolean}){
  const router=useRouter();const[editing,setEditing]=useState(false);const[mode,setMode]=useState<"default"|"unlimited"|"custom"|"profile">("default");const[profileId,setProfileId]=useState(profiles[0]?.id||"");const[download,setDownload]=useState(downloadBps?String(Number(downloadBps)/1e6):"20");const[upload,setUpload]=useState(uploadBps?String(Number(uploadBps)/1e6):"10");const[loading,setLoading]=useState(false);const[error,setError]=useState("");
  const save=async()=>{setLoading(true);setError("");try{await api(`/api/peers/${peerId}/bandwidth`,{method:"PUT",body:JSON.stringify({mode,profileId:mode==="profile"?profileId:null,downloadMbps:mode==="custom"?Number(download):null,uploadMbps:mode==="custom"?Number(upload):null})});setEditing(false);router.refresh()}catch(caught){setError(caught instanceof Error?caught.message:"Bandwidth update failed")}finally{setLoading(false)}};
  return <section id="bandwidth" className="card bandwidth-card"><div className="card-header"><div><h2><Gauge/> Bandwidth</h2><p>Traffic speed shaping is independent from quota usage.</p></div><StatusBadge status={syncState}/></div><div className="card-body"><div className="bandwidth-facts"><div><span>Download limit</span><strong>{formatRate(downloadBps)}</strong></div><div><span>Upload limit</span><strong>{formatRate(uploadBps)}</strong></div><div><span>Source</span><strong>{sourceName}</strong><small>{source.replaceAll("_"," ")}</small></div><div><span>Router queue</span><strong>{syncState==="synced"?(downloadBps&&uploadBps?"Active":"Not required"):syncState.replaceAll("_"," ")}</strong></div></div>{canManage&&(editing?<div className="bandwidth-editor"><div className="form-grid"><label className="form-group"><span className="label">Policy</span><select className="field" value={mode} onChange={event=>setMode(event.target.value as typeof mode)}><option value="default">Use default</option><option value="unlimited">Unlimited</option><option value="profile">Bandwidth profile</option><option value="custom">Custom</option></select></label>{mode==="profile"&&<label className="form-group"><span className="label">Profile</span><select className="field" value={profileId} onChange={event=>setProfileId(event.target.value)}>{profiles.map(profile=><option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label>}{mode==="custom"&&<><label className="form-group"><span className="label">Download Mbps</span><input className="field" type="number" min="0.001" step="0.001" value={download} onChange={event=>setDownload(event.target.value)}/></label><label className="form-group"><span className="label">Upload Mbps</span><input className="field" type="number" min="0.001" step="0.001" value={upload} onChange={event=>setUpload(event.target.value)}/></label></>}</div>{error&&<div className="form-message form-message-error">{error}</div>}<div className="button-row"><button className="button" onClick={()=>setEditing(false)}>Cancel</button><button className="button button-primary" disabled={loading||mode==="profile"&&!profileId} onClick={save}>{loading?<LoaderCircle className="spin"/>:<Save/>}Apply and verify</button></div></div>:<div className="button-row"><button className="button button-small" onClick={()=>setEditing(true)}><Wrench/>Change bandwidth</button>{syncState!=="synced"&&<button className="button button-small button-primary" onClick={()=>{setMode("default");setEditing(true)}}>Repair policy</button>}</div>)}</div></section>;
}
function formatRate(value:string|null){if(!value)return"Unlimited";const amount=Number(value);return amount>=1e9?`${amount/1e9} Gbps`:amount>=1e6?`${amount/1e6} Mbps`:`${amount/1e3} Kbps`}
