"use client";
/* eslint-disable @next/next/no-img-element -- protected QR endpoint requires the user's session and must bypass image optimization */

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Clipboard, Download, Edit3, KeyRound, LoaderCircle, Power, PowerOff, QrCode, Trash2, X } from "lucide-react";
import { api } from "@/lib/client-api";

type Peer={id:string;name:string;description:string;allowedAddress:string;clientAllowedIps:string;dnsServer:string;persistentKeepalive:number;mtu:number;expiresAt:string|null;endpointOverride:string;endpointPortOverride:number|null;disabled:boolean;managed:boolean};
export function PeerDetailActions({peer}:{peer:Peer}){const router=useRouter();const [busy,setBusy]=useState("");const [error,setError]=useState("");const [qr,setQr]=useState(false);const [config,setConfig]=useState("");const [edit,setEdit]=useState(false);
 const action=async(value:"enable"|"disable"|"delete")=>{if(value==="delete"&&!confirm(`Permanently delete ${peer.name} from the MikroTik and local database?`))return;setBusy(value);setError("");try{await api(`/api/peers/${peer.id}/action`,{method:"POST",body:JSON.stringify({action:value})});if(value==="delete")router.push("/peers");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy("")}};
 const reveal=async()=>{setBusy("config");setError("");try{const response=await fetch(`/api/peers/${peer.id}/config`,{cache:"no-store"});if(!response.ok){const body=await response.json();throw new Error(body.error)}setConfig(await response.text())}catch(e){setError(e instanceof Error?e.message:"Configuration unavailable")}finally{setBusy("")}};
 return <><div className="actions">{peer.managed&&<><a className="button button-primary" href={`/api/peers/${peer.id}/config`}><Download/>Download config</a><button className="button" onClick={()=>setQr(true)}><QrCode/>Show QR</button><button className="button" onClick={reveal} disabled={!!busy}>{busy==="config"?<LoaderCircle className="spin"/>:<Clipboard/>}Copy config</button></>}<button className="button" onClick={()=>action(peer.disabled?"enable":"disable")} disabled={!!busy}>{peer.disabled?<Power/>:<PowerOff/>}{peer.disabled?"Enable":"Disable"}</button><button className="button" onClick={()=>setEdit(true)}><Edit3/>Edit</button>{peer.managed&&<button className="button" onClick={async()=>{if(!confirm("Regenerate this peer's key material? Existing client configurations will stop working immediately."))return;setBusy("regenerate");try{await api(`/api/peers/${peer.id}/regenerate`,{method:"POST",body:JSON.stringify({usePresharedKey:false})});router.refresh()}catch(e){setError(e instanceof Error?e.message:"Regeneration failed")}finally{setBusy("")}}}><KeyRound/>Regenerate</button>}<button className="button button-danger" onClick={()=>action("delete")} disabled={!!busy}>{busy==="delete"?<LoaderCircle className="spin"/>:<Trash2/>}Delete</button></div>{error&&<div className="form-message form-message-error" style={{marginTop:10}}>{error}</div>}
 {config&&<div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true"><header className="dialog-header"><div><h2>Client configuration</h2><p>Sensitive. Close it when finished.</p></div><button className="button button-ghost icon-button" aria-label="Close configuration" onClick={()=>setConfig("")}><X/></button></header><div className="dialog-body"><pre className="code-block">{config}</pre></div><footer className="dialog-footer"><button className="button" onClick={async()=>{await navigator.clipboard.writeText(config)}}><Clipboard/>Copy</button><button className="button button-primary" onClick={()=>setConfig("")}>Done</button></footer></section></div>}
 {qr&&<div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true"><header className="dialog-header"><div><h2>{peer.name} QR code</h2><p>Scan with the official WireGuard mobile app.</p></div><button className="button button-ghost icon-button" aria-label="Close QR code" onClick={()=>setQr(false)}><X/></button></header><div className="dialog-body" style={{textAlign:"center"}}>{/* The protected, no-store QR endpoint cannot be fetched by Next image optimization without the user's session. */}<img src={`/api/peers/${peer.id}/qr`} alt={`WireGuard configuration QR code for ${peer.name}`} width={768} height={768} loading="lazy" style={{width:"min(100%,480px)",height:"auto",borderRadius:12}}/></div><footer className="dialog-footer"><a className="button button-primary" href={`/api/peers/${peer.id}/qr?download=1`}><Download/>Download PNG</a></footer></section></div>}
 {edit&&<PeerEditDialog peer={peer} close={()=>setEdit(false)}/>}</>}

function PeerEditDialog({peer,close}:{peer:Peer;close:()=>void}){const router=useRouter();const [loading,setLoading]=useState(false);const [error,setError]=useState("");return <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="peer-editor-title"><header className="dialog-header"><div><h2 id="peer-editor-title">Edit peer</h2><p>RouterOS state is checked again before the change is applied.</p></div><button className="button button-ghost icon-button" aria-label="Close peer editor" onClick={close}><X/></button></header><form onSubmit={async e=>{e.preventDefault();setLoading(true);const f=new FormData(e.currentTarget);try{await api(`/api/peers/${peer.id}`,{method:"PUT",body:JSON.stringify({name:f.get("name"),description:f.get("description"),allowedAddress:f.get("allowedAddress"),clientAllowedIps:f.get("clientAllowedIps"),dnsServer:f.get("dnsServer"),persistentKeepalive:Number(f.get("persistentKeepalive")),mtu:Number(f.get("mtu")),expiresAt:f.get("expiresAt")?new Date(String(f.get("expiresAt"))).toISOString():null,endpointOverride:f.get("endpointOverride")||null,endpointPortOverride:f.get("endpointPortOverride")?Number(f.get("endpointPortOverride")):null})});close();router.refresh()}catch(err){setError(err instanceof Error?err.message:"Save failed")}finally{setLoading(false)}}}><div className="dialog-body form"><div className="form-grid"><Form label="Name" name="name" value={peer.name}/><Form label="Allowed address" name="allowedAddress" value={peer.allowedAddress} mono/><Form label="Client AllowedIPs" name="clientAllowedIps" value={peer.clientAllowedIps} mono/><Form label="DNS server" name="dnsServer" value={peer.dnsServer}/><Form label="Keepalive" name="persistentKeepalive" value={String(peer.persistentKeepalive)} type="number"/><Form label="MTU" name="mtu" value={String(peer.mtu)} type="number"/><Form label="Endpoint override" name="endpointOverride" value={peer.endpointOverride}/><Form label="Endpoint port override" name="endpointPortOverride" value={peer.endpointPortOverride?.toString()||""} type="number"/><Form label="Expiration" name="expiresAt" value={peer.expiresAt?peer.expiresAt.slice(0,16):""} type="datetime-local"/><div className="form-group span-2"><label className="label" htmlFor="peer-edit-description">Description</label><textarea id="peer-edit-description" className="field" name="description" defaultValue={peer.description}/></div></div>{error&&<div className="form-message form-message-error">{error}</div>}</div><footer className="dialog-footer"><button type="button" className="button" onClick={close}>Cancel</button><button className="button button-primary" disabled={loading}>{loading?<LoaderCircle className="spin"/>:<Edit3/>}Save changes</button></footer></form></section></div>}
function Form({label,name,value,type="text",mono=false}:{label:string;name:string;value:string;type?:string;mono?:boolean}){const id=`peer-edit-${name}`;return <div className="form-group"><label className="label" htmlFor={id}>{label}</label><input id={id} className={`field ${mono?"mono":""}`} name={name} defaultValue={value} type={type}/></div>}
