"use client";
import { useState } from "react";
import { LoaderCircle, Plus, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/client-api";

type BandwidthProfile={id:string;name:string;description:string|null;downloadBps:string|null;uploadBps:string|null;system:boolean};
type PeerProfile={id:string;name:string;description:string|null;poolId:string|null;poolName:string|null;dns:string|null;clientAllowedIps:string|null;quotaBytes:string|null;quotaPeriod:string|null;bandwidthProfileId:string|null;bandwidthName:string|null;expirationDays:number|null};
type Pool={id:string;name:string};

export function GlobalBandwidthForm({mode,downloadBps,uploadBps,affected}:{mode:"unlimited"|"custom";downloadBps:string|null;uploadBps:string|null;affected:number}){
  const router=useRouter();const[current,setCurrent]=useState(mode);const[applyExisting,setApplyExisting]=useState(false);const[loading,setLoading]=useState(false);const[message,setMessage]=useState("");
  return <form className="form" onSubmit={async(event)=>{event.preventDefault();setLoading(true);setMessage("");const form=new FormData(event.currentTarget);try{const result=await api<{updated:number;retained:number;failed:Array<unknown>}>("/api/settings/bandwidth",{method:"PUT",body:JSON.stringify({mode:current,downloadMbps:current==="custom"?Number(form.get("downloadMbps")):null,uploadMbps:current==="custom"?Number(form.get("uploadMbps")):null,applyExisting,expectedPeerCount:affected})});setMessage(result.failed.length?`${result.updated} updated; ${result.failed.length} failed and need attention.`:applyExisting?`Saved; ${result.updated} existing peers updated.`:`Saved for new users; ${result.retained} existing peers retained their previous policy.`);router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Update failed")}finally{setLoading(false)}}}>
    <div className="form-grid"><label className="form-group"><span className="label">Global default</span><select className="field" value={current} onChange={event=>setCurrent(event.target.value as typeof current)}><option value="unlimited">Unlimited</option><option value="custom">Custom limit</option></select></label>{current==="custom"&&<><label className="form-group"><span className="label">Maximum download</span><div className="input-pair"><input className="field" name="downloadMbps" type="number" min="0.001" step="0.001" defaultValue={downloadBps?Number(downloadBps)/1e6:20} required/><span className="field input-suffix">Mbps</span></div></label><label className="form-group"><span className="label">Maximum upload</span><div className="input-pair"><input className="field" name="uploadMbps" type="number" min="0.001" step="0.001" defaultValue={uploadBps?Number(uploadBps)/1e6:10} required/><span className="field input-suffix">Mbps</span></div></label></>}</div>
    <label className="checkbox"><input type="checkbox" checked={applyExisting} onChange={event=>setApplyExisting(event.target.checked)}/><span>Apply to {affected} existing peer{affected===1?"":"s"} currently inheriting the global default</span></label>
    {applyExisting&&<div className="change-preview"><strong>Change preview</strong><span>{affected} queues may be created, updated, or removed. Custom, profile, and router-level policies will not be touched.</span></div>}
    {message&&<div className="form-message" role="status">{message}</div>}<button className="button button-primary" disabled={loading}>{loading?<LoaderCircle className="spin"/>:<Save/>}Save bandwidth default</button>
  </form>;
}

export function PolicyProfiles({bandwidthProfiles,peerProfiles,pools}:{bandwidthProfiles:BandwidthProfile[];peerProfiles:PeerProfile[];pools:Pool[]}){
  const router=useRouter();const[tab,setTab]=useState<"bandwidth"|"peer">("bandwidth");const[loading,setLoading]=useState(false);const[error,setError]=useState("");
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);try{if(tab==="bandwidth")await api("/api/bandwidth-profiles",{method:"POST",body:JSON.stringify({name:form.get("name"),description:form.get("description")||null,downloadMbps:form.get("downloadMbps")?Number(form.get("downloadMbps")):null,uploadMbps:form.get("uploadMbps")?Number(form.get("uploadMbps")):null,enabled:true})});else await api("/api/peer-profiles",{method:"POST",body:JSON.stringify({name:form.get("name"),description:form.get("description")||null,poolId:form.get("poolId")||null,dns:form.get("dns")||null,clientAllowedIps:form.get("allowedIps")||null,mtu:form.get("mtu")?Number(form.get("mtu")):null,keepalive:form.get("keepalive")?Number(form.get("keepalive")):null,quotaGb:form.get("quotaGb")?Number(form.get("quotaGb")):null,quotaPeriod:form.get("quotaPeriod")||null,bandwidthProfileId:form.get("bandwidthProfileId")||null,expirationDays:form.get("expirationDays")?Number(form.get("expirationDays")):null,enabled:true})});event.currentTarget.reset();router.refresh()}catch(caught){setError(caught instanceof Error?caught.message:"Profile creation failed")}finally{setLoading(false)}};
  return <div><div className="segmented-control"><button className={tab==="bandwidth"?"active":""} onClick={()=>setTab("bandwidth")}>Bandwidth profiles</button><button className={tab==="peer"?"active":""} onClick={()=>setTab("peer")}>User profiles</button></div>
    <div className="profile-grid">{(tab==="bandwidth"?bandwidthProfiles:peerProfiles).map(profile=><article className="profile-card" key={profile.id}><div><strong>{profile.name}</strong><p>{profile.description||"No description"}</p></div>{tab==="bandwidth"?<div className="policy-value">{(profile as BandwidthProfile).downloadBps?`${formatRate((profile as BandwidthProfile).downloadBps)} ↓ / ${formatRate((profile as BandwidthProfile).uploadBps)} ↑`:"Unlimited"}</div>:<dl><dt>Pool</dt><dd>{(profile as PeerProfile).poolName||"Router default"}</dd><dt>Bandwidth</dt><dd>{(profile as PeerProfile).bandwidthName||"Inherited"}</dd><dt>Quota</dt><dd>{(profile as PeerProfile).quotaBytes?`${formatBytes((profile as PeerProfile).quotaBytes!)} ${(profile as PeerProfile).quotaPeriod}`:"Inherited / unlimited"}</dd></dl>}</article>)}</div>
    <details className="advanced-settings profile-create"><summary><Plus/>Create {tab==="bandwidth"?"bandwidth":"user"} profile</summary><form className="form advanced-settings-body" onSubmit={submit}><div className="form-grid"><Field name="name" label="Profile name" placeholder={tab==="bandwidth"?"Sample 25 Mbps":"Sample Subscriber"}/><Field name="description" label="Description" optional/>{tab==="bandwidth"?<><Field name="downloadMbps" label="Download Mbps" type="number" optional/><Field name="uploadMbps" label="Upload Mbps" type="number" optional/></>:<><label className="form-group"><span className="label">WireGuard pool</span><select className="field" name="poolId"><option value="">Router default</option>{pools.map(pool=><option key={pool.id} value={pool.id}>{pool.name}</option>)}</select></label><label className="form-group"><span className="label">Bandwidth profile</span><select className="field" name="bandwidthProfileId"><option value="">Inherited</option>{bandwidthProfiles.map(profile=><option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label><Field name="dns" label="DNS" optional/><Field name="allowedIps" label="AllowedIPs" optional/><Field name="mtu" label="MTU" type="number" optional/><Field name="keepalive" label="Keepalive" type="number" optional/><Field name="quotaGb" label="Quota GB" type="number" optional/><label className="form-group"><span className="label">Quota period</span><select className="field" name="quotaPeriod"><option value="">Inherited</option><option value="one_time">Total</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><Field name="expirationDays" label="Expiration days" type="number" optional/></>}</div>{error&&<div className="form-message form-message-error">{error}</div>}<button className="button button-primary" disabled={loading}>{loading?<LoaderCircle className="spin"/>:<Plus/>}Create profile</button></form></details>
  </div>;
}
function Field({name,label,placeholder,type="text",optional=false}:{name:string;label:string;placeholder?:string;type?:string;optional?:boolean}){return <label className="form-group"><span className="label">{label}</span><input className="field" name={name} placeholder={placeholder} type={type} required={!optional}/></label>}
function formatRate(value:string|null){if(!value)return"—";const n=Number(value);return n>=1e9?`${n/1e9}G`:n>=1e6?`${n/1e6}M`:`${n/1e3}K`}function formatBytes(value:string){const n=Number(value);return n>=1e12?`${(n/1e12).toFixed(1)} TB`:`${(n/1e9).toFixed(1)} GB`}
