"use client";
import { useMemo, useState } from "react";
import { LoaderCircle, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/client-api";

type Option={id:string;name:string;interfaceId?:string};
type Initial={interfaceId:string|null;poolId:string|null;dns:string|null;allowedIps:string|null;endpoint:string|null;mtu:number|null;keepalive:number|null;quotaBytes:string|null;quotaPeriod:string|null;bandwidthMode:"global"|"unlimited"|"custom";downloadBps:string|null;uploadBps:string|null;expirationDays:number|null};
export function RouterDefaultsForm({routerId,interfaces,pools,initial}:{routerId:string;interfaces:Option[];pools:Option[];initial:Initial}){
  const router=useRouter();const[interfaceId,setInterfaceId]=useState(initial.interfaceId||"");const[poolId,setPoolId]=useState(initial.poolId||"");const[bandwidthMode,setBandwidthMode]=useState(initial.bandwidthMode);const[loading,setLoading]=useState(false);const[message,setMessage]=useState("");const visiblePools=useMemo(()=>pools.filter(pool=>pool.interfaceId===interfaceId),[pools,interfaceId]);
  return <form className="form" onSubmit={async(event)=>{event.preventDefault();setLoading(true);setMessage("");const form=new FormData(event.currentTarget);try{await api(`/api/routers/${routerId}/defaults`,{method:"PUT",body:JSON.stringify({interfaceId:interfaceId||null,poolId:poolId||null,dns:form.get("dns")||null,clientAllowedIps:form.get("allowedIps")||null,endpoint:form.get("endpoint")||null,mtu:form.get("mtu")?Number(form.get("mtu")):null,keepalive:form.get("keepalive")?Number(form.get("keepalive")):null,quotaGb:form.get("quotaGb")?Number(form.get("quotaGb")):null,quotaPeriod:form.get("quotaPeriod")||null,bandwidthMode,downloadMbps:bandwidthMode==="custom"?Number(form.get("downloadMbps")):null,uploadMbps:bandwidthMode==="custom"?Number(form.get("uploadMbps")):null,expirationDays:form.get("expirationDays")?Number(form.get("expirationDays")):null})});setMessage("Router defaults saved.");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Save failed")}finally{setLoading(false)}}}>
    <div className="form-grid"><label className="form-group"><span className="label">Default interface</span><select className="field" value={interfaceId} onChange={event=>{setInterfaceId(event.target.value);setPoolId("")}}><option value="">Choose during peer creation</option>{interfaces.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="form-group"><span className="label">Default WireGuard pool</span><select className="field" value={poolId} onChange={event=>setPoolId(event.target.value)}><option value="">Choose during peer creation</option>{visiblePools.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><Field name="dns" label="Default DNS" value={initial.dns}/><Field name="allowedIps" label="Default client AllowedIPs" value={initial.allowedIps}/><Field name="endpoint" label="Default endpoint" value={initial.endpoint}/><Field name="mtu" label="Default MTU" value={initial.mtu} type="number"/><Field name="keepalive" label="Default keepalive" value={initial.keepalive} type="number"/><Field name="quotaGb" label="Default quota (GB)" value={initial.quotaBytes?Number(initial.quotaBytes)/1e9:null} type="number"/><label className="form-group"><span className="label">Quota period</span><select className="field" name="quotaPeriod" defaultValue={initial.quotaPeriod||"monthly"}><option value="one_time">Total</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label className="form-group"><span className="label">Default bandwidth</span><select className="field" value={bandwidthMode} onChange={event=>setBandwidthMode(event.target.value as typeof bandwidthMode)}><option value="global">Use global default</option><option value="unlimited">Unlimited</option><option value="custom">Custom</option></select></label>{bandwidthMode==="custom"&&<><Field name="downloadMbps" label="Download Mbps" value={initial.downloadBps?Number(initial.downloadBps)/1e6:null} type="number" required/><Field name="uploadMbps" label="Upload Mbps" value={initial.uploadBps?Number(initial.uploadBps)/1e6:null} type="number" required/></>}<Field name="expirationDays" label="Default expiration (days)" value={initial.expirationDays} type="number"/></div>{message&&<div className="form-message" role="status">{message}</div>}<button className="button button-primary" disabled={loading}>{loading?<LoaderCircle className="spin"/>:<Save/>}Save router defaults</button>
  </form>;
}
function Field({name,label,value,type="text",required=false}:{name:string;label:string;value:string|number|null;type?:string;required?:boolean}){return <label className="form-group"><span className="label">{label}</span><input className="field" name={name} type={type} defaultValue={value??""} min={type==="number"?0.001:undefined} step={type==="number"?"any":undefined} required={required}/></label>}
