"use client";
import {useState} from "react";
import {LoaderCircle,Plus,Save} from "lucide-react";
import {useRouter} from "next/navigation";
import {api} from "@/lib/client-api";

type Role="super_admin"|"administrator"|"read_only";
type User={id:string;username:string;role:Role;enabled:boolean;lastLoginAt:string|null;createdAt:string};
export function UserManagement({users,currentUserId}:{users:User[];currentUserId:string}){const router=useRouter();const[loading,setLoading]=useState("");const[message,setMessage]=useState("");return <div className="user-management"><details className="advanced-settings profile-create"><summary><Plus/>Create account</summary><form className="form advanced-settings-body" onSubmit={async event=>{event.preventDefault();setLoading("create");setMessage("");const form=new FormData(event.currentTarget);try{await api("/api/users",{method:"POST",body:JSON.stringify({username:form.get("username"),password:form.get("password"),role:form.get("role")})});event.currentTarget.reset();setMessage("Account created.");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Account creation failed")}finally{setLoading("")}}}><div className="form-grid"><label className="form-group"><span className="label">Username</span><input className="field" name="username" minLength={3} maxLength={64} autoComplete="off" required/></label><label className="form-group"><span className="label">Temporary password</span><input className="field" name="password" type="password" minLength={12} maxLength={256} autoComplete="new-password" required/></label><label className="form-group"><span className="label">Role</span><select className="field" name="role" defaultValue="administrator"><RoleOptions/></select></label></div><p className="hint">Passwords require at least 12 characters. Send credentials through a secure channel outside this application.</p><button className="button button-primary" disabled={loading==="create"}>{loading==="create"?<LoaderCircle className="spin"/>:<Plus/>}Create account</button></form></details>{message&&<div className="form-message" role="status">{message}</div>}<div className="table-wrap" style={{marginTop:16}}><table><thead><tr><th>Username</th><th>Role</th><th>Enabled</th><th>Last login</th><th>Created</th><th>New password</th><th><span className="sr-only">Save</span></th></tr></thead><tbody>{users.map(user=><UserRow key={user.id} user={user} self={user.id===currentUserId} loading={loading===user.id} onStart={()=>{setLoading(user.id);setMessage("")}} onDone={message=>{setLoading("");setMessage(message);router.refresh()}}/>)}</tbody></table></div></div>}

function UserRow({user,self,loading,onStart,onDone}:{user:User;self:boolean;loading:boolean;onStart:()=>void;onDone:(message:string)=>void}){const[role,setRole]=useState<Role>(user.role);const[enabled,setEnabled]=useState(user.enabled);const[password,setPassword]=useState("");return <tr><td><strong>{user.username}</strong>{self&&<div className="cell-sub">Current session</div>}</td><td><select className="field field-compact" value={role} disabled={self||loading} onChange={event=>setRole(event.target.value as Role)} aria-label={`Role for ${user.username}`}><RoleOptions/></select></td><td><label className="checkbox"><input type="checkbox" checked={enabled} disabled={self||loading} onChange={event=>setEnabled(event.target.checked)}/><span>{enabled?"Enabled":"Disabled"}</span></label></td><td>{user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString():"Never"}</td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td><input className="field field-compact" type="password" value={password} minLength={12} maxLength={256} autoComplete="new-password" placeholder="Leave unchanged" onChange={event=>setPassword(event.target.value)} aria-label={`New password for ${user.username}`}/></td><td><button className="button button-small" disabled={loading||password.length>0&&password.length<12} onClick={async()=>{onStart();try{await api(`/api/users/${user.id}`,{method:"PUT",body:JSON.stringify({role,enabled,password:password||null})});setPassword("");onDone(`${user.username} updated. Existing sessions were revoked when access changed.`)}catch(error){onDone(error instanceof Error?error.message:"Account update failed")}}}>{loading?<LoaderCircle className="spin"/>:<Save/>}Save</button></td></tr>}
function RoleOptions(){return <><option value="super_admin">Super Admin</option><option value="administrator">Administrator</option><option value="read_only">Read Only</option></>}
